version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto@sha256:0e0886befecf2bf77e2e613f926f6ee0b77b93f76e49847471177143a8b3863c
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto_dev/config:/mosquitto/config
      - ./mosquitto_dev/data:/mosquitto/data
      - ./mosquitto_dev/log:/mosquitto/log
  postgres:
    container_name: postgres
    image: postgres@sha256:5a90725b3751c2c7ac311c9384dfc1a8f6e41823e341fb1dceed96a11677303a
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
