version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto@sha256:29c92f9144d4e65f7e647694d4b6aa7f0ac6a995bd102251ea05f7edf258ad20
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  postgres:
    container_name: postgres
    image: postgres@sha256:3458bdc7f5c7fdc3b54547c9cfd531e0097d1d434699a781f2c2aa1247906b74
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  backend:
    container_name: backend
    image: ghcr.io/hyperrtls/hyperrtls-backend:latest
    depends_on:
      - mosquitto
      - postgres
    labels:
      - "traefik.enable=true"
      # Middlewares
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.forceSlash=false"
      # Main router
      - "traefik.http.routers.main.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.main.entrypoints=websecure"
      - "traefik.http.routers.main.middlewares=backend-stripprefix@docker"
      - "traefik.http.routers.main.tls=true"
      - "traefik.http.routers.main.service=backend"
      # Backend-specific router
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
      # Services
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.services.backend.loadbalancer.server.scheme=http"
    environment:
      - DYNSEC_BROKER_URL
      - DYNSEC_BROKER_USERNAME
      - DYNSEC_BROKER_PASSWORD
      - MQTT_BROKER_URL
      - MQTT_BROKER_USERNAME
      - MQTT_BROKER_PASSWORD
      - DATABASE_URL
  traefik:
    container_name: traefik
    image: traefik:v2.9@sha256:2e53e47b59bc9a799b6c7b0d6d65f529de478094781751f1e061516ce9ca7c68
    command: 
      # - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock