version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto@sha256:29c92f9144d4e65f7e647694d4b6aa7f0ac6a995bd102251ea05f7edf258ad20
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8883:8883
  postgres:
    container_name: postgres
    image: postgres@sha256:3458bdc7f5c7fdc3b54547c9cfd531e0097d1d434699a781f2c2aa1247906b74
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
  backend:
    container_name: backend
    image: ghcr.io/hyperrtls/hyperrtls-backend:latest@sha256:785449a69a704efcae564f50b17e9a5800b44f2664eab6b5f2d4739df346e473
    depends_on:
      - mosquitto
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      # Middlewares
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.forceSlash=false"
      # Backend-specific router
      - "traefik.http.routers.backend.rule=((Host(`localhost`) && PathPrefix(`/api`)) || Host(`backend.localhost`))"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
      # - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix@docker"
      # Services
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.services.backend.loadbalancer.server.scheme=http"
    environment:
      - DYNSEC_BROKER_URL
      - DYNSEC_BROKER_USERNAME
      - DYNSEC_BROKER_PASSWORD
      - MQTT_BROKER_URL
      - MQTT_BROKER_USERNAME
      - MQTT_BROKER_PASSWORD
      - DATABASE_URL
  dashboard:
    container_name: dashboard
    image: ghcr.io/hyperrtls/hyperrtls-dashboard:latest@sha256:9bf2f7b38e9db5af48246b5353e3186c5be495bb3cc78b9dccea69d5a5156de8
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      # Dashboard-specific router
      - "traefik.http.routers.dashboard.rule=(Host(`localhost`) || Host(`dashboard.localhost`))"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      # - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=dashboard"
      # Services
      - "traefik.http.services.dashboard.loadbalancer.server.port=3000"
      - "traefik.http.services.dashboard.loadbalancer.server.scheme=http"
    environment:
      - SERVER_API_URL
      - CLIENT_API_URL
  traefik:
    container_name: traefik
    image: traefik:v2.9@sha256:2e53e47b59bc9a799b6c7b0d6d65f529de478094781751f1e061516ce9ca7c68
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 8081:80
      # - 8082:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock