version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto@sha256:bf5fb92712be8660ef6a204bf7a966c8f81f37d2b91a91432b9faaebf49c49d3
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto_dev/config:/mosquitto/config
      - ./mosquitto_dev/data:/mosquitto/data
      - ./mosquitto_dev/log:/mosquitto/log
  postgres:
    container_name: postgres
    image: postgres@sha256:5a90725b3751c2c7ac311c9384dfc1a8f6e41823e341fb1dceed96a11677303a
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
